/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Dark mode colors
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-primary": "#732ee4",
        "tertiary-container": "#a15100",
        "error-container": "#93000a",
        "background": "#15121b",
        "tertiary-fixed": "#ffdcc6",
        "on-background": "#e8dfee",
        "surface-container-high": "#2c2833",
        "surface-container-highest": "#37333e",
        "on-secondary-fixed": "#001e2c",
        "surface-variant": "#37333e",
        "tertiary-fixed-dim": "#ffb784",
        "on-tertiary-fixed-variant": "#713700",
        "primary-fixed": "#eaddff",
        "surface-tint": "#d2bbff",
        "tertiary": "#ffb784",
        "inverse-on-surface": "#332f39",
        "surface-container": "#221e28",
        "outline-variant": "#4a4455",
        "secondary-fixed": "#c4e7ff",
        "on-primary": "#3f008e",
        "secondary": "#7bd0ff",
        "error": "#ffb4ab",
        "surface": "#15121b",
        "secondary-container": "#00a6e0",
        "primary-container": "#7c3aed",
        "on-error": "#690005",
        "surface-dim": "#15121b",
        "surface-container-low": "#1d1a24",
        "surface-bright": "#3c3742",
        "on-tertiary-container": "#ffe0cd",
        "on-secondary": "#00354a",
        "outline": "#958da1",
        "primary": "#d2bbff",
        "on-primary-fixed": "#25005a",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#00374d",
        "secondary-fixed-dim": "#7bd0ff",
        "on-secondary-fixed-variant": "#004c69",
        "on-surface": "#e8dfee",
        "surface-container-lowest": "#100d16",
        "on-surface-variant": "#ccc3d8",
        "on-primary-container": "#ede0ff",
        "on-tertiary": "#4f2500",
        "primary-fixed-dim": "#d2bbff",
        "on-tertiary-fixed": "#301400",
        "inverse-surface": "#e8dfee",
        
        // Light mode colors
        light: {
          "background": "#faf9fc",
          "on-background": "#1c1b1f",
          "surface": "#faf9fc",
          "on-surface": "#1c1b1f",
          "primary": "#6750a4",
          "on-primary": "#ffffff",
          "primary-container": "#e8def8",
          "on-primary-container": "#21005e",
          "secondary": "#006495",
          "on-secondary": "#ffffff",
          "secondary-container": "#c9e6ff",
          "on-secondary-container": "#001e30",
          "tertiary": "#7d5260",
          "on-tertiary": "#ffffff",
          "tertiary-container": "#ffd8e4",
          "on-tertiary-container": "#31111d",
          "outline": "#79747e",
          "outline-variant": "#c4c7c5",
          "surface-variant": "#e7e0ec",
          "on-surface-variant": "#49454f",
        }
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "container-max": "1280px",
        "gutter": "24px",
        "unit-xs": "4px",
        "unit-sm": "8px",
        "margin-mobile": "20px",
        "unit-xxl": "128px",
        "unit-xl": "64px",
        "unit-lg": "32px",
        "unit-md": "16px"
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-lg": ["Poppins"],
        "code": ["monospace"],
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Poppins"],
        "body-md": ["Inter"],
        "headline-xl": ["Poppins"],
        "display-lg": ["Poppins"],
        "headline-sm": ["Poppins"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "code": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
